site_name: StatGuard Documentation
site_description: Documentacion tecnica de StatGuard
site_url: https://cjuol.github.io/statguard/
theme:
  name: material
  language: es
nav:
  - Introduccion: index.md
  - Fundamentos matematicos: math-basis.md
  - Referencia API: api-reference.md
  - Benchmarks: benchmarks.md
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
